name: Prepare and send summary
description: Add summary message to pipeline and notify TG
inputs:
  message:
    description: File content
    required: true
  to:
    description: Telegram Bot Token
    required: true
  token:
    description: Telegram Chat ID
    required: true
  thread_id:
    description: Telegram forum topic (message thread) ID
    required: false

runs:
  using: "composite"
  steps:
    - name: Create summary file
      uses: 1arp/create-a-file-action@0.4.5
      with:
        file: summary.md
        content: ${{ inputs.message }}

    - name: Read file
      id: read_file
      shell: bash
      run: |
        content=$(cat summary.md)
        echo "summary_message<<EOF" >> $GITHUB_OUTPUT
        echo "$content" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
        
        echo "$content" >> $GITHUB_STEP_SUMMARY

    - name: Send message to Telegram
      uses: appleboy/telegram-action@master
      with:
        to: ${{ inputs.to }}
        token: ${{ inputs.token }}
        message_thread_id: ${{ inputs.thread_id }}
        format: markdown
        message: ${{ steps.read_file.outputs.summary_message }}
