name: Setup
description: Setup project
runs:
  using: composite
  steps:
    - name: Setup JDK
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17
        cache: gradle
        check-latest: true

    - name: Set up cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle
          ~/app/build
          ~/core/build
          ~/model/build
          ~/.cache
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
