/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: PDA NETWORK API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package net.artux.pda.models.apis

import net.artux.pda.models.models.FriendModel
import net.artux.pda.models.models.Status
import retrofit2.http.GET
import retrofit2.http.Headers
import retrofit2.http.POST

@JvmSuppressWildcards
interface _Api {
    /**
     * Запросить/добавить/удалить друга
     * The endpoint is owned by defaultname service owner
     * @param pdaId pdaId (required)
     */
    @Headers(
        "X-Operation-ID: addFriendUsingPOST",
      "Content-Type: application/json"
    )
    @POST("/pdanetwork/profile/friends")
    suspend fun addFriendUsingPOST(
        @retrofit2.http.Query("pdaId") pdaId: Long
    ): Status
    /**
     * Получить запросы дружбы
     * The endpoint is owned by defaultname service owner
     */
    @Headers(
        "X-Operation-ID: getFriendsRequestsUsingGET"
    )
    @GET("/pdanetwork/profile/friends/requests")
    suspend fun getFriendsRequestsUsingGET(): List<FriendModel>
    /**
     * Получить друзей
     * The endpoint is owned by defaultname service owner
     */
    @Headers(
        "X-Operation-ID: getFriendsUsingGET"
    )
    @GET("/pdanetwork/profile/friends")
    suspend fun getFriendsUsingGET(): List<FriendModel>
    /**
     * Получить друзей по pdaId
     * The endpoint is owned by defaultname service owner
     * @param id id (required)
     */
    @Headers(
        "X-Operation-ID: getFriendsUsingGET_1"
    )
    @GET("/pdanetwork/profile/friends/{id}")
    suspend fun getFriendsUsingGET1(
        @retrofit2.http.Path("id") id: Long
    ): List<FriendModel>
    /**
     * Получить подписчиков
     * The endpoint is owned by defaultname service owner
     */
    @Headers(
        "X-Operation-ID: getSubsUsingGET"
    )
    @GET("/pdanetwork/profile/friends/subs")
    suspend fun getSubsUsingGET(): List<FriendModel>
    /**
     * Получить подписчиков по pdaId
     * The endpoint is owned by defaultname service owner
     * @param id id (required)
     */
    @Headers(
        "X-Operation-ID: getSubsUsingGET_1"
    )
    @GET("/pdanetwork/profile/friends/subs/{id}")
    suspend fun getSubsUsingGET1(
        @retrofit2.http.Path("id") id: Long
    ): List<FriendModel>
}
