name: Setup
description: Setup project
runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v3
    with:
      token: ${{secrets.token}}
      submodules: recursive

  - name: Get current date
    id: date
    run: echo "::set-output name=date::$(date +'%Y.%m')"

  - name: set up JDK 17
    uses: actions/setup-java@v2
    with:
      #architecture: 'aarch64'
      java-version: '17'
      distribution: 'temurin'
      cache: gradle

  - name: Setup Gradle
    uses: gradle/gradle-build-action@v2
    with:
      gradle-version: 8.2.1

  - name: Set up cache
    uses: actions/cache@v3
    with:
      path: |
        ~/.gradle/caches
        ~/.gradle/wrapper
        ~/.cache
      key: ${{ runner.os }}-android-${{ github.sha }}
      restore-keys: |
        ${{ runner.os }}-android-
