/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: PDA NETWORK API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package net.artux.pda.models.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property description
 * @property id
 * @property image
 * @property name
 * @property title
 * @property type
 */
@JsonClass(generateAdapter = true)
data class AchievementEntity(
    @Json(name = "description") @field:Json(name = "description") var description: String? = null,
    @Json(name = "id") @field:Json(name = "id") var id: Long? = null,
    @Json(name = "image") @field:Json(name = "image") var image: String? = null,
    @Json(name = "name") @field:Json(name = "name") var name: String? = null,
    @Json(name = "title") @field:Json(name = "title") var title: String? = null,
    @Json(name = "type") @field:Json(name = "type") var type: AchievementEntity.TypeEnum? = null
) {
    /**
     * Values: ADMINISTRATIVE, STATISTIC
     */
    @JsonClass(generateAdapter = false)
    enum class TypeEnum(val value: String) {
        @Json(name = "ADMINISTRATIVE") ADMINISTRATIVE("ADMINISTRATIVE"),
        @Json(name = "STATISTIC") STATISTIC("STATISTIC")
    }
}
