/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: PDA NETWORK API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package net.artux.pda.models.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property baseId
 * @property chemicalPr
 * @property condition
 * @property damagePr
 * @property electricPr
 * @property icon
 * @property id
 * @property owner
 * @property price
 * @property psyPr
 * @property quantity
 * @property radioPr
 * @property thermalPr
 * @property title
 * @property type
 * @property weight
 */
@JsonClass(generateAdapter = true)
data class ArmorEntity(
    @Json(name = "baseId") @field:Json(name = "baseId") var baseId: Int? = null,
    @Json(name = "chemical_pr") @field:Json(name = "chemical_pr") var chemicalPr: Float? = null,
    @Json(name = "condition") @field:Json(name = "condition") var condition: Float? = null,
    @Json(name = "damage_pr") @field:Json(name = "damage_pr") var damagePr: Float? = null,
    @Json(name = "electric_pr") @field:Json(name = "electric_pr") var electricPr: Float? = null,
    @Json(name = "icon") @field:Json(name = "icon") var icon: String? = null,
    @Json(name = "id") @field:Json(name = "id") var id: Long? = null,
    @Json(name = "owner") @field:Json(name = "owner") var owner: UserEntity? = null,
    @Json(name = "price") @field:Json(name = "price") var price: Int? = null,
    @Json(name = "psy_pr") @field:Json(name = "psy_pr") var psyPr: Float? = null,
    @Json(name = "quantity") @field:Json(name = "quantity") var quantity: Int? = null,
    @Json(name = "radio_pr") @field:Json(name = "radio_pr") var radioPr: Float? = null,
    @Json(name = "thermal_pr") @field:Json(name = "thermal_pr") var thermalPr: Float? = null,
    @Json(name = "title") @field:Json(name = "title") var title: String? = null,
    @Json(name = "type") @field:Json(name = "type") var type: ArmorEntity.TypeEnum? = null,
    @Json(name = "weight") @field:Json(name = "weight") var weight: Float? = null
) {
    /**
     * Values: ARMOR, ARTIFACT, DETECTOR, ITEM, MEDICINE, PISTOL, RIFLE
     */
    @JsonClass(generateAdapter = false)
    enum class TypeEnum(val value: String) {
        @Json(name = "ARMOR") ARMOR("ARMOR"),
        @Json(name = "ARTIFACT") ARTIFACT("ARTIFACT"),
        @Json(name = "DETECTOR") DETECTOR("DETECTOR"),
        @Json(name = "ITEM") ITEM("ITEM"),
        @Json(name = "MEDICINE") MEDICINE("MEDICINE"),
        @Json(name = "PISTOL") PISTOL("PISTOL"),
        @Json(name = "RIFLE") RIFLE("RIFLE")
    }
}
