/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: PDA NETWORK API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package net.artux.pda.models.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property anomalyId
 * @property baseId
 * @property bleeding
 * @property chemical
 * @property damage
 * @property electric
 * @property endurance
 * @property health
 * @property icon
 * @property id
 * @property owner
 * @property price
 * @property quantity
 * @property radio
 * @property thermal
 * @property title
 * @property type
 * @property weight
 */
@JsonClass(generateAdapter = true)
data class ArtifactEntity(
    @Json(name = "anomalyId") @field:Json(name = "anomalyId") var anomalyId: Int? = null,
    @Json(name = "baseId") @field:Json(name = "baseId") var baseId: Int? = null,
    @Json(name = "bleeding") @field:Json(name = "bleeding") var bleeding: Int? = null,
    @Json(name = "chemical") @field:Json(name = "chemical") var chemical: Int? = null,
    @Json(name = "damage") @field:Json(name = "damage") var damage: Int? = null,
    @Json(name = "electric") @field:Json(name = "electric") var electric: Int? = null,
    @Json(name = "endurance") @field:Json(name = "endurance") var endurance: Int? = null,
    @Json(name = "health") @field:Json(name = "health") var health: Int? = null,
    @Json(name = "icon") @field:Json(name = "icon") var icon: String? = null,
    @Json(name = "id") @field:Json(name = "id") var id: Long? = null,
    @Json(name = "owner") @field:Json(name = "owner") var owner: UserEntity? = null,
    @Json(name = "price") @field:Json(name = "price") var price: Int? = null,
    @Json(name = "quantity") @field:Json(name = "quantity") var quantity: Int? = null,
    @Json(name = "radio") @field:Json(name = "radio") var radio: Int? = null,
    @Json(name = "thermal") @field:Json(name = "thermal") var thermal: Int? = null,
    @Json(name = "title") @field:Json(name = "title") var title: String? = null,
    @Json(name = "type") @field:Json(name = "type") var type: ArtifactEntity.TypeEnum? = null,
    @Json(name = "weight") @field:Json(name = "weight") var weight: Float? = null
) {
    /**
     * Values: ARMOR, ARTIFACT, DETECTOR, ITEM, MEDICINE, PISTOL, RIFLE
     */
    @JsonClass(generateAdapter = false)
    enum class TypeEnum(val value: String) {
        @Json(name = "ARMOR") ARMOR("ARMOR"),
        @Json(name = "ARTIFACT") ARTIFACT("ARTIFACT"),
        @Json(name = "DETECTOR") DETECTOR("DETECTOR"),
        @Json(name = "ITEM") ITEM("ITEM"),
        @Json(name = "MEDICINE") MEDICINE("MEDICINE"),
        @Json(name = "PISTOL") PISTOL("PISTOL"),
        @Json(name = "RIFLE") RIFLE("RIFLE")
    }
}
