/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: PDA NETWORK API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package net.artux.pda.models.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property avatar
 * @property gang
 * @property login
 * @property pdaId
 */
@JsonClass(generateAdapter = true)
data class FriendModel(
    @Json(name = "avatar") @field:Json(name = "avatar") var avatar: String? = null,
    @Json(name = "gang") @field:Json(name = "gang") var gang: FriendModel.GangEnum? = null,
    @Json(name = "login") @field:Json(name = "login") var login: String? = null,
    @Json(name = "pdaId") @field:Json(name = "pdaId") var pdaId: Int? = null
) {
    /**
     * Values: BANDITS, CLEAR_SKY, DUTY, LIBERTY, LONERS, MERCENARIES, MILITARY, MONOLITH, SCIENTISTS
     */
    @JsonClass(generateAdapter = false)
    enum class GangEnum(val value: String) {
        @Json(name = "BANDITS") BANDITS("BANDITS"),
        @Json(name = "CLEAR_SKY") CLEAR_SKY("CLEAR_SKY"),
        @Json(name = "DUTY") DUTY("DUTY"),
        @Json(name = "LIBERTY") LIBERTY("LIBERTY"),
        @Json(name = "LONERS") LONERS("LONERS"),
        @Json(name = "MERCENARIES") MERCENARIES("MERCENARIES"),
        @Json(name = "MILITARY") MILITARY("MILITARY"),
        @Json(name = "MONOLITH") MONOLITH("MONOLITH"),
        @Json(name = "SCIENTISTS") SCIENTISTS("SCIENTISTS")
    }
}
