/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: PDA NETWORK API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package net.artux.pda.models.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property bandits
 * @property clearSky
 * @property duty
 * @property id
 * @property liberty
 * @property loners
 * @property mercenaries
 * @property military
 * @property monolith
 * @property scientists
 * @property user
 */
@JsonClass(generateAdapter = true)
data class GangRelationEntity(
    @Json(name = "bandits") @field:Json(name = "bandits") var bandits: Int? = null,
    @Json(name = "clearSky") @field:Json(name = "clearSky") var clearSky: Int? = null,
    @Json(name = "duty") @field:Json(name = "duty") var duty: Int? = null,
    @Json(name = "id") @field:Json(name = "id") var id: Long? = null,
    @Json(name = "liberty") @field:Json(name = "liberty") var liberty: Int? = null,
    @Json(name = "loners") @field:Json(name = "loners") var loners: Int? = null,
    @Json(name = "mercenaries") @field:Json(name = "mercenaries") var mercenaries: Int? = null,
    @Json(name = "military") @field:Json(name = "military") var military: Int? = null,
    @Json(name = "monolith") @field:Json(name = "monolith") var monolith: Int? = null,
    @Json(name = "scientists") @field:Json(name = "scientists") var scientists: Int? = null,
    @Json(name = "user") @field:Json(name = "user") var user: UserEntity? = null
)
