/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: PDA NETWORK API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package net.artux.pda.models.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property author
 * @property content
 * @property id
 * @property time
 * @property title
 */
@JsonClass(generateAdapter = true)
data class NoteEntity(
    @Json(name = "author") @field:Json(name = "author") var author: UserEntity? = null,
    @Json(name = "content") @field:Json(name = "content") var content: String? = null,
    @Json(name = "id") @field:Json(name = "id") var id: Long? = null,
    @Json(name = "time") @field:Json(name = "time") var time: Long? = null,
    @Json(name = "title") @field:Json(name = "title") var title: String? = null
)
