/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: PDA NETWORK API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package net.artux.pda.models.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property avatar
 * @property email
 * @property login
 * @property name
 * @property nickname
 * @property password
 */
@JsonClass(generateAdapter = true)
data class RegisterUser(
    @Json(name = "avatar") @field:Json(name = "avatar") var avatar: String? = null,
    @Json(name = "email") @field:Json(name = "email") var email: String? = null,
    @Json(name = "login") @field:Json(name = "login") var login: String? = null,
    @Json(name = "name") @field:Json(name = "name") var name: String? = null,
    @Json(name = "nickname") @field:Json(name = "nickname") var nickname: String? = null,
    @Json(name = "password") @field:Json(name = "password") var password: String? = null
)
