/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: PDA NETWORK API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package net.artux.pda.models.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property `data`
 * @property dataSize
 * @property lastPage
 * @property number
 * @property queryDataSize
 * @property size
 * @property sortBy
 * @property sortDirection
 */
@JsonClass(generateAdapter = true)
data class ResponsePage_UserInfo_(
    @Json(name = "data") @field:Json(name = "data") var `data`: List<UserInfo>? = null,
    @Json(name = "dataSize") @field:Json(name = "dataSize") var dataSize: Int? = null,
    @Json(name = "lastPage") @field:Json(name = "lastPage") var lastPage: Int? = null,
    @Json(name = "number") @field:Json(name = "number") var number: Int? = null,
    @Json(name = "queryDataSize") @field:Json(name = "queryDataSize") var queryDataSize: Long? = null,
    @Json(name = "size") @field:Json(name = "size") var size: Int? = null,
    @Json(name = "sortBy") @field:Json(name = "sortBy") var sortBy: String? = null,
    @Json(name = "sortDirection") @field:Json(name = "sortDirection") var sortDirection: ResponsePage_UserInfo_.SortDirectionEnum? = null
) {
    /**
     * Values: ASC, DESC
     */
    @JsonClass(generateAdapter = false)
    enum class SortDirectionEnum(val value: String) {
        @Json(name = "ASC") ASC("ASC"),
        @Json(name = "DESC") DESC("DESC")
    }
}
