/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: PDA NETWORK API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package net.artux.pda.models.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property allItems
 * @property armorEntities
 * @property artifactEntities
 * @property avatar
 * @property id
 * @property itemEntities
 * @property name
 * @property pistols
 * @property rifles
 */
@JsonClass(generateAdapter = true)
data class SellerDto(
    @Json(name = "allItems") @field:Json(name = "allItems") var allItems: List<ItemEntity>? = null,
    @Json(name = "armorEntities") @field:Json(name = "armorEntities") var armorEntities: List<ArmorEntity>? = null,
    @Json(name = "artifactEntities") @field:Json(name = "artifactEntities") var artifactEntities: List<ArtifactEntity>? = null,
    @Json(name = "avatar") @field:Json(name = "avatar") var avatar: String? = null,
    @Json(name = "id") @field:Json(name = "id") var id: Int? = null,
    @Json(name = "itemEntities") @field:Json(name = "itemEntities") var itemEntities: List<ItemEntity>? = null,
    @Json(name = "name") @field:Json(name = "name") var name: String? = null,
    @Json(name = "pistols") @field:Json(name = "pistols") var pistols: List<WeaponEntity>? = null,
    @Json(name = "rifles") @field:Json(name = "rifles") var rifles: List<WeaponEntity>? = null
)
