/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: PDA NETWORK API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package net.artux.pda.models.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property code
 * @property description
 * @property success
 */
@JsonClass(generateAdapter = true)
data class Status(
    @Json(name = "code") @field:Json(name = "code") var code: Int? = null,
    @Json(name = "description") @field:Json(name = "description") var description: String? = null,
    @Json(name = "success") @field:Json(name = "success") var success: Boolean? = null
)
