/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: PDA NETWORK API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package net.artux.pda.models.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property achievement
 * @property id
 * @property user
 */
@JsonClass(generateAdapter = true)
data class UserAchievementEntity(
    @Json(name = "achievement") @field:Json(name = "achievement") var achievement: AchievementEntity? = null,
    @Json(name = "id") @field:Json(name = "id") var id: Long? = null,
    @Json(name = "user") @field:Json(name = "user") var user: UserEntity? = null
)
