/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: PDA NETWORK API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package net.artux.pda.models.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property baseId
 * @property bulletId
 * @property bulletQuantity
 * @property condition
 * @property damage
 * @property icon
 * @property id
 * @property owner
 * @property precision
 * @property price
 * @property quantity
 * @property speed
 * @property title
 * @property type
 * @property weight
 */
@JsonClass(generateAdapter = true)
data class WeaponEntity(
    @Json(name = "baseId") @field:Json(name = "baseId") var baseId: Int? = null,
    @Json(name = "bulletId") @field:Json(name = "bulletId") var bulletId: Int? = null,
    @Json(name = "bulletQuantity") @field:Json(name = "bulletQuantity") var bulletQuantity: Int? = null,
    @Json(name = "condition") @field:Json(name = "condition") var condition: Float? = null,
    @Json(name = "damage") @field:Json(name = "damage") var damage: Float? = null,
    @Json(name = "icon") @field:Json(name = "icon") var icon: String? = null,
    @Json(name = "id") @field:Json(name = "id") var id: Long? = null,
    @Json(name = "owner") @field:Json(name = "owner") var owner: UserEntity? = null,
    @Json(name = "precision") @field:Json(name = "precision") var precision: Float? = null,
    @Json(name = "price") @field:Json(name = "price") var price: Int? = null,
    @Json(name = "quantity") @field:Json(name = "quantity") var quantity: Int? = null,
    @Json(name = "speed") @field:Json(name = "speed") var speed: Float? = null,
    @Json(name = "title") @field:Json(name = "title") var title: String? = null,
    @Json(name = "type") @field:Json(name = "type") var type: WeaponEntity.TypeEnum? = null,
    @Json(name = "weight") @field:Json(name = "weight") var weight: Float? = null
) {
    /**
     * Values: ARMOR, ARTIFACT, DETECTOR, ITEM, MEDICINE, PISTOL, RIFLE
     */
    @JsonClass(generateAdapter = false)
    enum class TypeEnum(val value: String) {
        @Json(name = "ARMOR") ARMOR("ARMOR"),
        @Json(name = "ARTIFACT") ARTIFACT("ARTIFACT"),
        @Json(name = "DETECTOR") DETECTOR("DETECTOR"),
        @Json(name = "ITEM") ITEM("ITEM"),
        @Json(name = "MEDICINE") MEDICINE("MEDICINE"),
        @Json(name = "PISTOL") PISTOL("PISTOL"),
        @Json(name = "RIFLE") RIFLE("RIFLE")
    }
}
