name: Android CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, x64]
    env:
      ANDROID_HOME: C:\android\sdk
      
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{secrets.token}}
        submodules: recursive

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 8.3
      
    - name: Build APK
      id: buildDebug
      run: ./gradlew assembleDebug
      
    - uses: r0adkll/sign-android-release@v1
      name: Sign APK
      id: sign_apk
      if: ${{ github.ref == 'refs/heads/master' }}
      with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.key_alias }}
          keyStorePassword: ${{ secrets.keystore_password }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
