name: Deploy Javadoc

on:
  push:
    branches:
      - master
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.6
      - name: Deploy JavaDoc 🚀
        uses: MathieuSoysal/Javadoc-publisher.yml@v2.3.0
        with:
            GITHUB_TOKEN: ${{secrets.token}}
            java-version: 11
            target-folder: 'javadoc'
            project: gradle
