name: Preview Build

on:
  workflow_dispatch:

jobs:
  build:
    name: Internal build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{secrets.token}}
          submodules: recursive

      - uses: ./.github/assembly
        id: assembly
        with:
          profile: preview
          signing_key: ${{ secrets.SIGNING_KEY }}
          key_alias: ${{ secrets.KEY_ALIAS }}
          keystore_password: ${{ secrets.KEYSTORE_PASSWORD }}
          key_password: ${{ secrets.KEY_PASSWORD }}
          service_account_json: ${{ secrets.SERVICE_ACCOUNT_JSON }}

      - name: Send message to Artux channel
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Preview сборка ${{github.run_number}}, версия ${{ steps.date.outputs.date }}-preview
            
            Ссылка для скачивания активна три месяца: 
            ${{steps.assembly.outputs.internalSharingDownloadUrls}}
            
            Изменения:
            ${{ github.event.head_commit.message }}
